version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - pandoc
  jobs:
    post_create_environment:
      - pip install poetry # Install Poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs # Install Dependencies
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
