[project]
name = "ggml-ot"
version = "0.1.0"
description = ""
authors = [
    {name = "damin",email = "damin.kuehn@rwth-aachen.de"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tqdm (>=4.67.1,<5.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "umap-learn (>=0.5.7,<0.6.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "scikit-learn (==1.5.1)",
    "gprofiler-official (>=1.0.0,<2.0.0)",
    "metric-learn (>=0.7.0,<0.8.0)",
    "pathlib (>=1.0.1,<2.0.0)",
    "pot (>=0.9.5,<0.10.0)",
    "pydiffmap (>=0.2.0.1,<0.3.0.0)",
    "python-voi (>=0.0.3,<0.0.4)",
    "scanpy (==1.10.4)",
    "anndata (>=0.11.4,<0.12.0)",
    "torch (>=2.6.0,<3.0.0)",
    "torchaudio (>=2.6.0,<3.0.0)",
    "torchvision (>=0.21.0,<0.22.0)"
]

[tool.poetry]
name = "ggml_ot"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"