[project]
name = "ggml-ot"
version = "0.1.0"
description = ""
authors = [
    {name = "damin",email = "damin.kuehn@rwth-aachen.de"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "ggml_ot", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
