name: Run Python tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix: # Python versions to test against
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with test
      - name: Lint with ruff
        run: |
          poetry run ruff check --config pyproject.toml
      - name: run tests
        run: |
          poetry run python -W "ignore::DeprecationWarning:ot.*" -m pytest --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
